using iTender.Compliance.Application.DTOs;
using iTender.Compliance.Application.Interfaces.Repositories;
using iTender.Compliance.Application.Interfaces.Services;
using iTender.Compliance.Domain.Enums;
using Microsoft.Extensions.Configuration;
using QuestPDF.Fluent;

namespace iTender.Compliance.Infrastructure.Services
{
    public class DocumentService : IDocumentService
    {
        private readonly string _rootFolder;
        private readonly string _logoPath;
        private readonly ICurrentUserService _currentUserService;
        private readonly ICorrespondenceTemplateRepository _templateRepository;
        public DocumentService(IConfiguration configuration, ICurrentUserService currentUserService, ICorrespondenceTemplateRepository templateRepository)
        {
            _rootFolder = configuration["Documents:RootFolder"]!;
            _logoPath = configuration["Documents:LogoPath"]!;

            if (!Directory.Exists(_rootFolder))
                Directory.CreateDirectory(_rootFolder);

            _currentUserService = currentUserService;
            _templateRepository = templateRepository;
        }

        public async Task<DocumentResult> GenerateInstructionLetterAsync(
    SendInstructionLetterModel model,
    CancellationToken cancellationToken = default)
        {
            var template = await _templateRepository.GetActiveAsync(
                CorrespondenceTemplateType.InstructionLetter);

            if (template == null)
                throw new InvalidOperationException(
                    "The Instruction Letter template has not been configured.");

            var subject = ReplacePlaceholders(template.Subject, model, _currentUserService.FullName);
            var body = ReplacePlaceholders(template.Body, model, _currentUserService.FullName);

            var safeTender = model.TenderNumber
                .Replace("/", "-")
                .Replace("\\", "-");

            var fileName =
                $"Instruction_{safeTender}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";

            var path = Path.Combine(_rootFolder, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Column(column =>
                        {
                            column.Item()
                                .Height(45)
                                .Image("wwwroot/cidb-logo.png");

                            column.Item()
                                .Text("CIDB Regulatory Compliance Intelligence Platform (CRCIP)")
                                .FontSize(10)
                                .FontColor("#666666");

                            column.Item()
                                .PaddingTop(8)
                                .LineHorizontal(1)
                                .LineColor("#B3202A");
                        });


                    page.Content()
                        .PaddingTop(20)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            column.Item()
                                .Text(body)
                                .FontSize(11);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by CIDB Regulatory Compliance Intelligence Platform (CRCIP) • Page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf(path);

            return new DocumentResult
            {
                FileName = fileName,
                FilePath = path
            };
        }
        public async Task<DocumentResult> GenerateReminderLetterAsync(SendReminderLetterModel model, CancellationToken cancellationToken = default)
        {
            var template = await _templateRepository.GetActiveAsync(
                CorrespondenceTemplateType.ReminderLetter);

            if (template == null)
                throw new InvalidOperationException(
                    "The Reminder Letter template has not been configured.");

            var subject = ReplacePlaceholdersReminder(template.Subject, model, _currentUserService.FullName);
            var body = ReplacePlaceholdersReminder(template.Body, model, _currentUserService.FullName);

            var safeTender = model.TenderNumber
                .Replace("/", "-")
                .Replace("\\", "-");

            var fileName =
                $"Reminder_{safeTender}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";

            var path = Path.Combine(_rootFolder, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Column(column =>
                        {
                            column.Item()
                                .Height(45)
                                .Image("wwwroot/cidb-logo.png");

                            column.Item()
                                .Text("CIDB Regulatory Compliance Intelligence Platform (CRCIP)")
                                .FontSize(10)
                                .FontColor("#666666");

                            column.Item()
                                .PaddingTop(8)
                                .LineHorizontal(1)
                                .LineColor("#B3202A");
                        });


                    page.Content()
                        .PaddingTop(20)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            column.Item()
                                .Text(body)
                                .FontSize(11);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by CIDB Regulatory Compliance Intelligence Platform (CRCIP) • Page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf(path);

            return new DocumentResult
            {
                FileName = fileName,
                FilePath = path
            };
        }
        public async Task<DocumentResult> GenerateContraventionNoticeAsync(
            SendContraventionNoticeModel model,
            CancellationToken cancellationToken = default)
        {
            var template = await _templateRepository.GetActiveAsync(
                CorrespondenceTemplateType.ContraventionNotice);

            if (template == null)
                throw new InvalidOperationException(
                    "The Contravention Notice template has not been configured.");

            var subject = ReplacePlaceholdersContravention(template.Subject, model, _currentUserService.FullName);
            var body = ReplacePlaceholdersContravention(template.Body, model, _currentUserService.FullName);

            var safeTender = model.TenderNumber
                .Replace("/", "-")
                .Replace("\\", "-");

            var fileName =
                $"ContraventionNotice_{safeTender}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";

            var path = Path.Combine(_rootFolder, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Column(column =>
                        {
                            column.Item()
                                .Height(45)
                                .Image("wwwroot/cidb-logo.png");

                            column.Item()
                                .Text("CIDB Regulatory Compliance Intelligence Platform (CRCIP)")
                                .FontSize(10)
                                .FontColor("#666666");

                            column.Item()
                                .PaddingTop(8)
                                .LineHorizontal(1)
                                .LineColor("#B3202A");
                        });

                    page.Content()
                        .PaddingTop(20)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            column.Item()
                                .Text(body)
                                .FontSize(11);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by CIDB Regulatory Compliance Intelligence Platform (CRCIP) • Page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf(path);

            return new DocumentResult
            {
                FileName = fileName,
                FilePath = path
            };
        }

        public Task<DocumentResult> GenerateAgsaReferralDocumentAsync(
            AgsaReferralDocumentModel model,
            CancellationToken cancellationToken = default)
        {
            var safeTender = model.TenderNumber
                .Replace("/", "-")
                .Replace("\\", "-");

            var fileName =
                $"AGSAReferral_{safeTender}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";

            var path = Path.Combine(_rootFolder, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Row(row =>
                        {
                            var logo = File.Exists(_logoPath) ? _logoPath : null;

                            if (logo != null)
                                row.ConstantItem(120).Image(logo);

                            row.RelativeItem()
                                .Column(column =>
                                {
                                    column.Item()
                                        .Text("Referral for Enforcement")
                                        .FontSize(20)
                                        .Bold();

                                    column.Item()
                                        .Text($"Reference: {model.ReferralNumber}");
                                });
                        });

                    page.Content()
                        .PaddingTop(20)
                        .Column(column =>
                        {
                            column.Spacing(8);

                            column.Item().Text($"Tender Number: {model.TenderNumber}");
                            column.Item().Text($"Tender Title: {model.TenderTitle}");
                            column.Item().Text($"Employer: {model.EmployerName}");
                            column.Item().Text($"Referral Date: {model.ReferralDate:dd MMM yyyy}");
                            column.Item().PaddingTop(10).Text("Reason for Referral").Bold();
                            column.Item().Text(model.Reason);

                            if (!string.IsNullOrWhiteSpace(model.Description))
                            {
                                column.Item().PaddingTop(10).Text("Description").Bold();
                                column.Item().Text(model.Description);
                            }
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by CIDB Regulatory Compliance Intelligence Platform (CRCIP) • Page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf(path);

            return Task.FromResult(new DocumentResult
            {
                FileName = fileName,
                FilePath = path
            });
        }

        private static string ReplacePlaceholders(string template, SendInstructionLetterModel model, string user)
        {
            return template
                .Replace("{CompanyName}", model.RecipientName)
                .Replace("{ContactPerson}", model.RecipientName)
                .Replace("{TenderNumber}", model.TenderNumber)
                .Replace("{TenderTitle}", model.TenderTitle)
                .Replace("{EmployerName}", model.EmployerName)
                .Replace("{ClosingDate}", model.ClosingDate.ToString("dd MMM yyyy"))
                .Replace("{ResponseDueDate}", model.ResponseDueOn.ToString("dd MMM yyyy"))
                .Replace("{AgentName}", user)
                .Replace("{FooterText}", model.FooterText ?? string.Empty)
                .Replace("{CurrentDate}", DateTime.Now.ToString("dd MMM yyyy"));
            // {Manager_Signature} is intentionally left unreplaced - it is the literal
            // anchor text SigningHub's autoplace API searches the PDF for.
        }

        private static string ReplacePlaceholdersContravention(string template, SendContraventionNoticeModel model, string user)
        {
            return template
                .Replace("{CompanyName}", model.RecipientName)
                .Replace("{ContactPerson}", model.RecipientName)
                .Replace("{TenderNumber}", model.TenderNumber)
                .Replace("{TenderTitle}", model.TenderTitle)
                .Replace("{EmployerName}", model.EmployerName)
                .Replace("{ClosingDate}", model.ClosingDate.ToString("dd MMM yyyy"))
                .Replace("{ResponseDueDate}", model.ResponseDueOn.ToString("dd MMM yyyy"))
                .Replace("{Reason}", model.Reason)
                .Replace("{AgentName}", user)
                .Replace("{FooterText}", model.FooterText ?? string.Empty)
                .Replace("{CurrentDate}", DateTime.Now.ToString("dd MMM yyyy"));
            // {Manager_Signature} is intentionally left unreplaced - see above.
        }

        private static string ReplacePlaceholdersReminder(string template, SendReminderLetterModel model, string user)
        {
            return template
                .Replace("{CompanyName}", model.RecipientName)
                .Replace("{ContactPerson}", model.RecipientName)
                .Replace("{TenderNumber}", model.TenderNumber)
                .Replace("{TenderTitle}", model.TenderTitle)
                .Replace("{EmployerName}", model.EmployerName)
                .Replace("{ClosingDate}", model.ClosingDate.ToString("dd MMM yyyy"))
                .Replace("{ResponseDueDate}", model.ResponseDueOn.ToString("dd MMM yyyy"))
                .Replace("{AgentName}", user)
                .Replace("{CurrentDate}", DateTime.Now.ToString("dd MMM yyyy"));
        }
    }
}