using iTender.Compliance.Application.DTOs;
using iTender.Compliance.Application.Interfaces.Repositories;
using iTender.Compliance.Application.Interfaces.Services;
using iTender.Compliance.Domain.Enums;
using Microsoft.Extensions.Configuration;
using QuestPDF.Fluent;

namespace iTender.Compliance.Infrastructure.Services
{
    public class DocumentService : IDocumentService
    {
        private readonly string _rootFolder;
        private readonly string _logoPath;
        private readonly ICurrentUserService _currentUserService;
        private readonly ICorrespondenceTemplateRepository _templateRepository;
        public DocumentService(IConfiguration configuration, ICurrentUserService currentUserService, ICorrespondenceTemplateRepository templateRepository)
        {
            _rootFolder = configuration["Documents:RootFolder"]!;
            _logoPath = configuration["Documents:LogoPath"]!;

            if (!Directory.Exists(_rootFolder))
                Directory.CreateDirectory(_rootFolder);

            _currentUserService = currentUserService;
            _templateRepository = templateRepository;
        }

        public async Task<DocumentResult> GenerateInstructionLetterAsync(
    SendInstructionLetterModel model,
    CancellationToken cancellationToken = default)
        {
            var template = await _templateRepository.GetByTypeAsync(
                CorrespondenceTemplateType.InstructionLetter,
                cancellationToken);

            if (template == null)
                throw new InvalidOperationException(
                    "The Instruction Letter template has not been configured.");

            var subject = ReplacePlaceholders(template.Subject, model, _currentUserService.FullName);
            var body = ReplacePlaceholders(template.Body, model, _currentUserService.FullName);

            var safeTender = model.TenderNumber
                .Replace("/", "-")
                .Replace("\\", "-");

            var fileName =
                $"Instruction_{safeTender}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";

            var path = Path.Combine(_rootFolder, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Row(row =>
                        {
                            var logo = !string.IsNullOrWhiteSpace(template.HeaderImagePath)
                                && File.Exists(template.HeaderImagePath)
                                ? template.HeaderImagePath
                                : _logoPath;

                            row.ConstantItem(120)
                                .Image(logo);

                            row.RelativeItem()
                                .Column(column =>
                                {
                                    column.Item()
                                        .Text(subject)
                                        .FontSize(20)
                                        .Bold();

                                    column.Item()
                                        .Text($"Generated {DateTime.Now:dd MMM yyyy}");
                                });
                        });;

                    page.Content()
                        .PaddingTop(20)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            column.Item()
                                .Text(body)
                                .FontSize(11);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by iTender Compliance • Page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf(path);

            return new DocumentResult
            {
                FileName = fileName,
                FilePath = path
            };
        }
        public async Task<DocumentResult> GenerateReminderLetterAsync(SendReminderLetterModel model, CancellationToken cancellationToken = default)
        {
            var template = await _templateRepository.GetByTypeAsync(
                CorrespondenceTemplateType.ReminderLetter,
                cancellationToken);

            if (template == null)
                throw new InvalidOperationException(
                    "The Reminder Letter template has not been configured.");

            var subject = ReplacePlaceholdersReminder(template.Subject, model, _currentUserService.FullName);
            var body = ReplacePlaceholdersReminder(template.Body, model, _currentUserService.FullName);

            var safeTender = model.TenderNumber
                .Replace("/", "-")
                .Replace("\\", "-");

            var fileName =
                $"Reminder_{safeTender}_{DateTime.UtcNow:yyyyMMddHHmmss}.pdf";

            var path = Path.Combine(_rootFolder, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(40);

                    page.Header()
                        .Column(column =>
                        {
                            if (!string.IsNullOrWhiteSpace(model.HeaderImagePath) &&
                                File.Exists(model.HeaderImagePath))
                            {
                                column.Item()
                                    .AlignCenter()
                                    .Image(model.HeaderImagePath);
                            }

                            column.Item()
                                .PaddingTop(10)
                                .Text(subject)
                                .FontSize(20)
                                .Bold();

                            column.Item()
                                .Text($"Generated {DateTime.Now:dd MMM yyyy}");
                        });

                    page.Content()
                        .PaddingTop(20)
                        .Column(column =>
                        {
                            column.Spacing(10);

                            column.Item()
                                .Text(body)
                                .FontSize(11);
                        });

                    page.Footer()
                        .AlignCenter()
                        .Text(text =>
                        {
                            text.Span("Generated by iTender Compliance • Page ");
                            text.CurrentPageNumber();
                            text.Span(" of ");
                            text.TotalPages();
                        });
                });
            })
            .GeneratePdf(path);

            return new DocumentResult
            {
                FileName = fileName,
                FilePath = path
            };
        }
        private static string ReplacePlaceholders(
    string template,
    SendInstructionLetterModel model,
    string user)
        {
            return template
                .Replace("{CompanyName}", model.RecipientName)
                .Replace("{ContactPerson}", model.RecipientName)
                .Replace("{TenderNumber}", model.TenderNumber)
                .Replace("{TenderTitle}", model.TenderTitle)
                .Replace("{EmployerName}", model.EmployerName)
                .Replace("{ClosingDate}", model.ClosingDate.ToString("dd MMM yyyy hh:mm tt"))
                .Replace("{ResponseDueDate}", model.ResponseDueOn.ToString("dd MMM yyyy hh:mm tt"))
                .Replace("{AgentName}", user)
                .Replace("{FooterText}", model.FooterText ?? string.Empty)
                .Replace("{CurrentDate}", DateTime.Now.ToString("dd MMM yyyy hh:mm tt"));
        }

        private static string ReplacePlaceholdersReminder(string template, SendReminderLetterModel model, string user)
        {
            return template
                .Replace("{CompanyName}", model.RecipientName)
                .Replace("{ContactPerson}", model.RecipientName)
                .Replace("{TenderNumber}", model.TenderNumber)
                .Replace("{TenderTitle}", model.TenderTitle)
                .Replace("{EmployerName}", model.EmployerName)
                .Replace("{ClosingDate}", model.ClosingDate.ToString("dd MMM yyyy hh:mm tt"))
                .Replace("{ResponseDueDate}", model.ResponseDueOn.ToString("dd MMM yyyy hh:mm tt"))
                .Replace("{AgentName}", user)
                .Replace("{FooterText}", model.FooterText ?? string.Empty)
                .Replace("{CurrentDate}", DateTime.Now.ToString("dd MMM yyyy hh:mm tt"));
        }
    }
}
